using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;
using System.Xml;
using Common.Types;
namespace Common.Types
{
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "MusicVenue")]
    public partial class MusicVenue { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "VideoObject")]
    public partial class VideoObject { }
    [XmlType(Namespace = "http://schema.org/Quantity", TypeName = "Duration")]
    public partial class Duration { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "WPHeader")]
    public partial class WPHeader { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "RVPark")]
    public partial class RVPark { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "MusicVideoObject")]
    public partial class MusicVideoObject { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MovieRentalStore")]
    public partial class MovieRentalStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "SkiResort")]
    public partial class SkiResort { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "OceanBodyOfWater")]
    public partial class OceanBodyOfWater { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "TattooParlor")]
    public partial class TattooParlor { }
    [XmlType(Namespace = "http://schema.org/Enumeration", TypeName = "ItemAvailability")]
    public partial class ItemAvailability { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "EntertainmentBusiness")]
    public partial class EntertainmentBusiness { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "EducationalOrganization")]
    public partial class EducationalOrganization { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AutomatedTeller")]
    public partial class AutomatedTeller { }
    [XmlType(Namespace = "http://schema.org/Offer", TypeName = "Offer")]
    public partial class Offer { }
    [XmlType(Namespace = "http://schema.org/Enumeration", TypeName = "OfferItemCondition")]
    public partial class OfferItemCondition { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ConvenienceStore")]
    public partial class ConvenienceStore { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "AboutPage")]
    public partial class AboutPage { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "WPFooter")]
    public partial class WPFooter { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "ImageObject")]
    public partial class ImageObject { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "SelfStorage")]
    public partial class SelfStorage { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AutomotiveBusiness")]
    public partial class AutomotiveBusiness { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "PoliceStation")]
    public partial class PoliceStation { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "PostOffice")]
    public partial class PostOffice { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Aquarium")]
    public partial class Aquarium { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserDownloads")]
    public partial class UserDownloads { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MotorcycleRepair")]
    public partial class MotorcycleRepair { }
    [XmlType(Namespace = "http://schema.org/StructuredValue", TypeName = "GeoCoordinates")]
    public partial class GeoCoordinates { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "AudioObject")]
    public partial class AudioObject { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Physician")]
    public partial class Physician { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "SearchResultsPage")]
    public partial class SearchResultsPage { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ComputerStore")]
    public partial class ComputerStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Restaurant")]
    public partial class Restaurant { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "WebPage")]
    public partial class WebPage { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "ProfilePage")]
    public partial class ProfilePage { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "MusicPlaylist")]
    public partial class MusicPlaylist { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "BeautySalon")]
    public partial class BeautySalon { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MusicStore")]
    public partial class MusicStore { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Crematorium")]
    public partial class Crematorium { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "SocialEvent")]
    public partial class SocialEvent { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "LodgingBusiness")]
    public partial class LodgingBusiness { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Bakery")]
    public partial class Bakery { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Landform")]
    public partial class Landform { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "StadiumOrArena")]
    public partial class StadiumOrArena { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Organization")]
    public partial class Organization { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "SaleEvent")]
    public partial class SaleEvent { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MiddleSchool")]
    public partial class MiddleSchool { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HardwareStore")]
    public partial class HardwareStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "FurnitureStore")]
    public partial class FurnitureStore { }
    [XmlType(Namespace = "http://schema.org/Rating", TypeName = "Rating")]
    public partial class Rating { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "SportsClub")]
    public partial class SportsClub { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "BlogPosting")]
    public partial class BlogPosting { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Volcano")]
    public partial class Volcano { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "MusicEvent")]
    public partial class MusicEvent { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "FoodEstablishment")]
    public partial class FoodEstablishment { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ComedyClub")]
    public partial class ComedyClub { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MedicalClinic")]
    public partial class MedicalClinic { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "TelevisionStation")]
    public partial class TelevisionStation { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "NightClub")]
    public partial class NightClub { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "CivicStructure")]
    public partial class CivicStructure { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Book")]
    public partial class Book { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MusicGroup")]
    public partial class MusicGroup { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ElementarySchool")]
    public partial class ElementarySchool { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Campground")]
    public partial class Campground { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "FoodEvent")]
    public partial class FoodEvent { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Playground")]
    public partial class Playground { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HairSalon")]
    public partial class HairSalon { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Synagogue")]
    public partial class Synagogue { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Courthouse")]
    public partial class Courthouse { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "PerformingArtsTheater")]
    public partial class PerformingArtsTheater { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "Festival")]
    public partial class Festival { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Recipe")]
    public partial class Recipe { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Hospital")]
    public partial class Hospital { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "NGO")]
    public partial class NGO { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Mosque")]
    public partial class Mosque { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "WPSideBar")]
    public partial class WPSideBar { }
    [XmlType(Namespace = "http://schema.org/Enumeration", TypeName = "Enumeration")]
    public partial class Enumeration { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Pharmacy")]
    public partial class Pharmacy { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "EducationEvent")]
    public partial class EducationEvent { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "State")]
    public partial class State { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "BikeStore")]
    public partial class BikeStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Electrician")]
    public partial class Electrician { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "PetStore")]
    public partial class PetStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "EmploymentAgency")]
    public partial class EmploymentAgency { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "TVEpisode")]
    public partial class TVEpisode { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "ItemPage")]
    public partial class ItemPage { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Locksmith")]
    public partial class Locksmith { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "GolfCourse")]
    public partial class GolfCourse { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AutoWash")]
    public partial class AutoWash { }
    [XmlType(Namespace = "http://schema.org/Offer", TypeName = "AggregateOffer")]
    public partial class AggregateOffer { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "RecyclingCenter")]
    public partial class RecyclingCenter { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "SingleFamilyResidence")]
    public partial class SingleFamilyResidence { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Park")]
    public partial class Park { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ClothingStore")]
    public partial class ClothingStore { }
    [XmlType(Namespace = "http://schema.org/StructuredValue", TypeName = "StructuredValue")]
    public partial class StructuredValue { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AutoRental")]
    public partial class AutoRental { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Waterfall")]
    public partial class Waterfall { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "NewsArticle")]
    public partial class NewsArticle { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Country")]
    public partial class Country { }
    [XmlType(Namespace = "http://schema.org/Enumeration", TypeName = "BookFormatType")]
    public partial class BookFormatType { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Article")]
    public partial class Article { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HomeAndConstructionBusiness")]
    public partial class HomeAndConstructionBusiness { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "ComedyEvent")]
    public partial class ComedyEvent { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "GovernmentOrganization")]
    public partial class GovernmentOrganization { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Plumber")]
    public partial class Plumber { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "MusicRecording")]
    public partial class MusicRecording { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HomeGoodsStore")]
    public partial class HomeGoodsStore { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserInteraction")]
    public partial class UserInteraction { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "TouristInformationCenter")]
    public partial class TouristInformationCenter { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserComments")]
    public partial class UserComments { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "GeneralContractor")]
    public partial class GeneralContractor { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "ItemList")]
    public partial class ItemList { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AutoRepair")]
    public partial class AutoRepair { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "TennisComplex")]
    public partial class TennisComplex { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "EventVenue")]
    public partial class EventVenue { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Place")]
    public partial class Place { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "WholesaleStore")]
    public partial class WholesaleStore { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "TrainStation")]
    public partial class TrainStation { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Hotel")]
    public partial class Hotel { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "WPAdBlock")]
    public partial class WPAdBlock { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AutoBodyShop")]
    public partial class AutoBodyShop { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HVACBusiness")]
    public partial class HVACBusiness { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "BarOrPub")]
    public partial class BarOrPub { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AutoPartsStore")]
    public partial class AutoPartsStore { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "CollectionPage")]
    public partial class CollectionPage { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MotorcycleDealer")]
    public partial class MotorcycleDealer { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "BodyOfWater")]
    public partial class BodyOfWater { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Reservoir")]
    public partial class Reservoir { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "DefenceEstablishment")]
    public partial class DefenceEstablishment { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "ApartmentComplex")]
    public partial class ApartmentComplex { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "DanceEvent")]
    public partial class DanceEvent { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "Event")]
    public partial class Event { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AnimalShelter")]
    public partial class AnimalShelter { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Embassy")]
    public partial class Embassy { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "HinduTemple")]
    public partial class HinduTemple { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "TVSeries")]
    public partial class TVSeries { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "ContactPage")]
    public partial class ContactPage { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Sculpture")]
    public partial class Sculpture { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ChildCare")]
    public partial class ChildCare { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AccountingService")]
    public partial class AccountingService { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "LiquorStore")]
    public partial class LiquorStore { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Continent")]
    public partial class Continent { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MensClothingStore")]
    public partial class MensClothingStore { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Canal")]
    public partial class Canal { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Mountain")]
    public partial class Mountain { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserPlays")]
    public partial class UserPlays { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ShoppingCenter")]
    public partial class ShoppingCenter { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "TireShop")]
    public partial class TireShop { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "TouristAttraction")]
    public partial class TouristAttraction { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HealthClub")]
    public partial class HealthClub { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Review")]
    public partial class Review { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MovingCompany")]
    public partial class MovingCompany { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "SportsActivityLocation")]
    public partial class SportsActivityLocation { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "LocalBusiness")]
    public partial class LocalBusiness { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "BookStore")]
    public partial class BookStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "VeterinaryCare")]
    public partial class VeterinaryCare { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MedicalOrganization")]
    public partial class MedicalOrganization { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Store")]
    public partial class Store { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "PerformingGroup")]
    public partial class PerformingGroup { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "DaySpa")]
    public partial class DaySpa { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserCheckins")]
    public partial class UserCheckins { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "DryCleaningOrLaundry")]
    public partial class DryCleaningOrLaundry { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "OfficeEquipmentStore")]
    public partial class OfficeEquipmentStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "InternetCafe")]
    public partial class InternetCafe { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "BusinessEvent")]
    public partial class BusinessEvent { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HobbyShop")]
    public partial class HobbyShop { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Dentist")]
    public partial class Dentist { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "GroceryStore")]
    public partial class GroceryStore { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Movie")]
    public partial class Movie { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "ImageGallery")]
    public partial class ImageGallery { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "CreativeWork")]
    public partial class CreativeWork { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "MediaObject")]
    public partial class MediaObject { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Preschool")]
    public partial class Preschool { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "SiteNavigationElement")]
    public partial class SiteNavigationElement { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ProfessionalService")]
    public partial class ProfessionalService { }
    [XmlType(Namespace = "http://schema.org/Language", TypeName = "Language")]
    public partial class Language { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "SubwayStation")]
    public partial class SubwayStation { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "SeaBodyOfWater")]
    public partial class SeaBodyOfWater { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Casino")]
    public partial class Casino { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "GovernmentOffice")]
    public partial class GovernmentOffice { }
    [XmlType(Namespace = "http://schema.org/Person", TypeName = "Person")]
    public partial class Person { }
    [XmlType(Namespace = "http://schema.org/Quantity", TypeName = "Mass")]
    public partial class Mass { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "SportingGoodsStore")]
    public partial class SportingGoodsStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Notary")]
    public partial class Notary { }
    [XmlType(Namespace = "http://schema.org/Rating", TypeName = "AggregateRating")]
    public partial class AggregateRating { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserPlusOnes")]
    public partial class UserPlusOnes { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Zoo")]
    public partial class Zoo { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Painting")]
    public partial class Painting { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "GardenStore")]
    public partial class GardenStore { }
    [XmlType(Namespace = "http://schema.org/Quantity", TypeName = "Quantity")]
    public partial class Quantity { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Blog")]
    public partial class Blog { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HealthAndBeautyBusiness")]
    public partial class HealthAndBeautyBusiness { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ArtGallery")]
    public partial class ArtGallery { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "NailSalon")]
    public partial class NailSalon { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "CatholicChurch")]
    public partial class CatholicChurch { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "BusStation")]
    public partial class BusStation { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Library")]
    public partial class Library { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "TheaterEvent")]
    public partial class TheaterEvent { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "MusicAlbum")]
    public partial class MusicAlbum { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "DepartmentStore")]
    public partial class DepartmentStore { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "AdministrativeArea")]
    public partial class AdministrativeArea { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "LakeBodyOfWater")]
    public partial class LakeBodyOfWater { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "FinancialService")]
    public partial class FinancialService { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "PlaceOfWorship")]
    public partial class PlaceOfWorship { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Church")]
    public partial class Church { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MobilePhoneStore")]
    public partial class MobilePhoneStore { }
    [XmlType(Namespace = "http://schema.org/StructuredValue", TypeName = "ContactPoint")]
    public partial class ContactPoint { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "OutletStore")]
    public partial class OutletStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AutoDealer")]
    public partial class AutoDealer { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "FastFoodRestaurant")]
    public partial class FastFoodRestaurant { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AmusementPark")]
    public partial class AmusementPark { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserBlocks")]
    public partial class UserBlocks { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "FireStation")]
    public partial class FireStation { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "GasStation")]
    public partial class GasStation { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Museum")]
    public partial class Museum { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "AdultEntertainment")]
    public partial class AdultEntertainment { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Corporation")]
    public partial class Corporation { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Motel")]
    public partial class Motel { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ElectronicsStore")]
    public partial class ElectronicsStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "TravelAgency")]
    public partial class TravelAgency { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserPageVisits")]
    public partial class UserPageVisits { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ShoeStore")]
    public partial class ShoeStore { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "LegislativeBuilding")]
    public partial class LegislativeBuilding { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "SportsEvent")]
    public partial class SportsEvent { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "GovernmentBuilding")]
    public partial class GovernmentBuilding { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "EmergencyService")]
    public partial class EmergencyService { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HousePainter")]
    public partial class HousePainter { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ToyStore")]
    public partial class ToyStore { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "IceCreamShop")]
    public partial class IceCreamShop { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "HighSchool")]
    public partial class HighSchool { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Beach")]
    public partial class Beach { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Brewery")]
    public partial class Brewery { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Map")]
    public partial class Map { }
    [XmlType(Namespace = "http://schema.org/Product", TypeName = "Product")]
    public partial class Product { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "CollegeOrUniversity")]
    public partial class CollegeOrUniversity { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "BuddhistTemple")]
    public partial class BuddhistTemple { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "RealEstateAgent")]
    public partial class RealEstateAgent { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserTweets")]
    public partial class UserTweets { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "RiverBodyOfWater")]
    public partial class RiverBodyOfWater { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "BedAndBreakfast")]
    public partial class BedAndBreakfast { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "CheckoutPage")]
    public partial class CheckoutPage { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "ScholarlyArticle")]
    public partial class ScholarlyArticle { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "CityHall")]
    public partial class CityHall { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "BowlingAlley")]
    public partial class BowlingAlley { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "ChildrensEvent")]
    public partial class ChildrensEvent { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "WebPageElement")]
    public partial class WebPageElement { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "TheaterGroup")]
    public partial class TheaterGroup { }
    [XmlType(Namespace = "http://schema.org/Quantity", TypeName = "Distance")]
    public partial class Distance { }
    [XmlType(Namespace = "http://schema.org/Quantity", TypeName = "Energy")]
    public partial class Energy { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "ExerciseGym")]
    public partial class ExerciseGym { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Optician")]
    public partial class Optician { }
    [XmlType(Namespace = "http://schema.org/StructuredValue", TypeName = "NutritionInformation")]
    public partial class NutritionInformation { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "JewelryStore")]
    public partial class JewelryStore { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Photograph")]
    public partial class Photograph { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Residence")]
    public partial class Residence { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "City")]
    public partial class City { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "GatedResidenceCommunity")]
    public partial class GatedResidenceCommunity { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "SportsTeam")]
    public partial class SportsTeam { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "RoofingContractor")]
    public partial class RoofingContractor { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "RadioStation")]
    public partial class RadioStation { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Florist")]
    public partial class Florist { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Airport")]
    public partial class Airport { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "CafeOrCoffeeShop")]
    public partial class CafeOrCoffeeShop { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "InsuranceAgency")]
    public partial class InsuranceAgency { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Winery")]
    public partial class Winery { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Pond")]
    public partial class Pond { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "VideoGallery")]
    public partial class VideoGallery { }
    [XmlType(Namespace = "http://schema.org/StructuredValue", TypeName = "PostalAddress")]
    public partial class PostalAddress { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "DanceGroup")]
    public partial class DanceGroup { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "ParkingFacility")]
    public partial class ParkingFacility { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Attorney")]
    public partial class Attorney { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "MovieTheater")]
    public partial class MovieTheater { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "PublicSwimmingPool")]
    public partial class PublicSwimmingPool { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "PawnShop")]
    public partial class PawnShop { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "LandmarksOrHistoricalBuildings")]
    public partial class LandmarksOrHistoricalBuildings { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "Cemetery")]
    public partial class Cemetery { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "TaxiStand")]
    public partial class TaxiStand { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "TVSeason")]
    public partial class TVSeason { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "BankOrCreditUnion")]
    public partial class BankOrCreditUnion { }
    [XmlType(Namespace = "http://schema.org/Intangible", TypeName = "Intangible")]
    public partial class Intangible { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "VisualArtsEvent")]
    public partial class VisualArtsEvent { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "School")]
    public partial class School { }
    [XmlType(Namespace = "http://schema.org/CreativeWork", TypeName = "Table")]
    public partial class Table { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "UserLikes")]
    public partial class UserLikes { }
    [XmlType(Namespace = "http://schema.org/Organization", TypeName = "Hostel")]
    public partial class Hostel { }
    [XmlType(Namespace = "http://schema.org/Event", TypeName = "LiteraryEvent")]
    public partial class LiteraryEvent { }
    [XmlType(Namespace = "http://schema.org/Place", TypeName = "BusStop")]
    public partial class BusStop { }
    [XmlType(Namespace = "http://schema.org/Thing", TypeName = "ElectronicPaymentCardData")]
    public partial class ElectronicPaymentCardData { }



}
